python get_examples.py -i dataset\9326871 -d examples_2
python get_examples.py -i dataset\9332898 -d examples_2
python get_examples.py -i dataset\9336923 -d examples_2
python get_examples.py -i dataset\9338446 -d examples_2
python get_examples.py -i dataset\9338454 -d examples_2
python get_examples.py -i dataset\9338462 -d examples_2
python get_examples.py -i dataset\9338489 -d examples_2
python get_examples.py -i dataset\9338497 -d examples_2
python get_examples.py -i dataset\9338519 -d examples_2
python get_examples.py -i dataset\9338527 -d examples_2
python get_examples.py -i dataset\9338535 -d examples_2
python get_examples.py -i dataset\9338543 -d examples_2
python get_examples.py -i dataset\9414649 -d examples_2
python get_examples.py -i dataset\9416994 -d examples_2
python get_examples.py -i dataset\adhast -d examples_2
python get_examples.py -i dataset\admars -d examples_2
python get_examples.py -i dataset\ahodki -d examples_2
python get_examples.py -i dataset\ajbake -d examples_2
python get_examples.py -i dataset\ajflem -d examples_2
python get_examples.py -i dataset\ajones -d examples_2
python get_examples.py -i dataset\ajsega -d examples_2
python get_examples.py -i dataset\akatsi -d examples_2
python get_examples.py -i dataset\alan_grant -d examples_2
python get_examples.py -i dataset\ambarw -d examples_2
python get_examples.py -i dataset\anonym -d examples_2
python get_examples.py -i dataset\anonym1 -d examples_2
python get_examples.py -i dataset\anonym2 -d examples_2
python get_examples.py -i dataset\anpage -d examples_2
python get_examples.py -i dataset\apapou -d examples_2
python get_examples.py -i dataset\apdavi -d examples_2
python get_examples.py -i dataset\ardper -d examples_2
python get_examples.py -i dataset\asamma -d examples_2
python get_examples.py -i dataset\asewil -d examples_2
python get_examples.py -i dataset\asheal -d examples_2
python get_examples.py -i dataset\astefa -d examples_2
python get_examples.py -i dataset\awjsud -d examples_2
python get_examples.py -i dataset\boylee -d examples_2
python get_examples.py -i dataset\bplyce -d examples_2
python get_examples.py -i dataset\bschap -d examples_2
python get_examples.py -i dataset\cadugd -d examples_2
python get_examples.py -i dataset\cchris -d examples_2
python get_examples.py -i dataset\ccjame -d examples_2
python get_examples.py -i dataset\cdlarg -d examples_2
python get_examples.py -i dataset\cferdo -d examples_2
python get_examples.py -i dataset\cfloro -d examples_2
python get_examples.py -i dataset\cgboyc -d examples_2
python get_examples.py -i dataset\chi_pu -d examples_2
python get_examples.py -i dataset\cjcarr -d examples_2
python get_examples.py -i dataset\cjdenn -d examples_2
python get_examples.py -i dataset\cjsake -d examples_2
python get_examples.py -i dataset\cladam -d examples_2
python get_examples.py -i dataset\cmkirk -d examples_2
python get_examples.py -i dataset\csanch -d examples_2
python get_examples.py -i dataset\cshubb -d examples_2
python get_examples.py -i dataset\cwang -d examples_2
python get_examples.py -i dataset\cwchoi -d examples_2
python get_examples.py -i dataset\cywan -d examples_2
python get_examples.py -i dataset\dagran -d examples_2
python get_examples.py -i dataset\dakram -d examples_2
python get_examples.py -i dataset\damvo -d examples_2
python get_examples.py -i dataset\darda -d examples_2
python get_examples.py -i dataset\dcbowe -d examples_2
python get_examples.py -i dataset\dfhodd -d examples_2
python get_examples.py -i dataset\dgemen -d examples_2
python get_examples.py -i dataset\dioann -d examples_2
python get_examples.py -i dataset\djbirc -d examples_2
python get_examples.py -i dataset\djhugh -d examples_2
python get_examples.py -i dataset\djmart -d examples_2
python get_examples.py -i dataset\dmwest -d examples_2
python get_examples.py -i dataset\doraj -d examples_2
python get_examples.py -i dataset\drbost -d examples_2
python get_examples.py -i dataset\ekavaz -d examples_2
python get_examples.py -i dataset\elduns -d examples_2
python get_examples.py -i dataset\fordj -d examples_2
python get_examples.py -i dataset\gdhatc -d examples_2
python get_examples.py -i dataset\ggeorg -d examples_2
python get_examples.py -i dataset\ggrego -d examples_2
python get_examples.py -i dataset\gjhero -d examples_2
python get_examples.py -i dataset\gjnorm -d examples_2
python get_examples.py -i dataset\gmwate -d examples_2
python get_examples.py -i dataset\gotone -d examples_2
python get_examples.py -i dataset\gpapaz -d examples_2
python get_examples.py -i dataset\gpsmit -d examples_2
python get_examples.py -i dataset\gsmall -d examples_2
python get_examples.py -i dataset\gsreas -d examples_2
python get_examples.py -i dataset\gstamo -d examples_2
python get_examples.py -i dataset\gsvird -d examples_2
python get_examples.py -i dataset\hartb -d examples_2
python get_examples.py -i dataset\hcarpe -d examples_2
python get_examples.py -i dataset\hensm -d examples_2
python get_examples.py -i dataset\howar -d examples_2
python get_examples.py -i dataset\hsgrim -d examples_2
python get_examples.py -i dataset\huynh_lap -d examples_2
python get_examples.py -i dataset\ieorf -d examples_2
python get_examples.py -i dataset\ijfran -d examples_2
python get_examples.py -i dataset\irdrew -d examples_2
python get_examples.py -i dataset\isbald -d examples_2
python get_examples.py -i dataset\jabins -d examples_2
python get_examples.py -i dataset\jagrif -d examples_2
python get_examples.py -i dataset\jbierl -d examples_2
python get_examples.py -i dataset\jcarte -d examples_2
python get_examples.py -i dataset\jdbenm -d examples_2
python get_examples.py -i dataset\jgloma -d examples_2
python get_examples.py -i dataset\jlemon -d examples_2
python get_examples.py -i dataset\jmedin -d examples_2
python get_examples.py -i dataset\jross -d examples_2
python get_examples.py -i dataset\jrtobi -d examples_2
python get_examples.py -i dataset\jserai -d examples_2
python get_examples.py -i dataset\jshea -d examples_2
python get_examples.py -i dataset\justin_bieber -d examples_2
python get_examples.py -i dataset\kaatki -d examples_2
python get_examples.py -i dataset\kaknig -d examples_2
python get_examples.py -i dataset\kbartl -d examples_2
python get_examples.py -i dataset\kdjone -d examples_2
python get_examples.py -i dataset\khchan -d examples_2
python get_examples.py -i dataset\khughe -d examples_2
python get_examples.py -i dataset\kjwith -d examples_2
python get_examples.py -i dataset\klclar -d examples_2
python get_examples.py -i dataset\kmbald -d examples_2
python get_examples.py -i dataset\kouri -d examples_2
python get_examples.py -i dataset\ksunth -d examples_2
python get_examples.py -i dataset\labenm -d examples_2
python get_examples.py -i dataset\ldgodd -d examples_2
python get_examples.py -i dataset\lejnno -d examples_2
python get_examples.py -i dataset\lfso -d examples_2
python get_examples.py -i dataset\lidov -d examples_2
python get_examples.py -i dataset\llambr -d examples_2
python get_examples.py -i dataset\lyond -d examples_2
python get_examples.py -i dataset\maasht -d examples_2
python get_examples.py -i dataset\macci -d examples_2
python get_examples.py -i dataset\martin -d examples_2
python get_examples.py -i dataset\matth -d examples_2
python get_examples.py -i dataset\mberdo -d examples_2
python get_examples.py -i dataset\mbutle -d examples_2
python get_examples.py -i dataset\mdchud -d examples_2
python get_examples.py -i dataset\mdpove -d examples_2
python get_examples.py -i dataset\mefait -d examples_2
python get_examples.py -i dataset\mhwill -d examples_2
python get_examples.py -i dataset\miaduc -d examples_2
python get_examples.py -i dataset\michael -d examples_2
python get_examples.py -i dataset\mizli -d examples_2
python get_examples.py -i dataset\mjhans -d examples_2
python get_examples.py -i dataset\mkosto -d examples_2
python get_examples.py -i dataset\moors -d examples_2
python get_examples.py -i dataset\mpetti -d examples_2
python get_examples.py -i dataset\muthay -d examples_2
python get_examples.py -i dataset\nahaig -d examples_2
python get_examples.py -i dataset\namull -d examples_2
python get_examples.py -i dataset\ndbank -d examples_2
python get_examples.py -i dataset\ndhagu -d examples_2
python get_examples.py -i dataset\ngo_kien_huy -d examples_2
python get_examples.py -i dataset\nhrams -d examples_2
python get_examples.py -i dataset\njmoor -d examples_2
python get_examples.py -i dataset\npbour -d examples_2
python get_examples.py -i dataset\npmitc -d examples_2
python get_examples.py -i dataset\nrclar -d examples_2
python get_examples.py -i dataset\nrrbar -d examples_2
python get_examples.py -i dataset\nwilli -d examples_2
python get_examples.py -i dataset\obeidn -d examples_2
python get_examples.py -i dataset\ohpark -d examples_2
python get_examples.py -i dataset\pacole -d examples_2
python get_examples.py -i dataset\phughe -d examples_2
python get_examples.py -i dataset\pmives -d examples_2
python get_examples.py -i dataset\pshurr -d examples_2
python get_examples.py -i dataset\pspliu -d examples_2
python get_examples.py -i dataset\ptnich -d examples_2
python get_examples.py -i dataset\rarobi -d examples_2
python get_examples.py -i dataset\rgharr -d examples_2
python get_examples.py -i dataset\rgspru -d examples_2
python get_examples.py -i dataset\rjlabr -d examples_2
python get_examples.py -i dataset\rlocke -d examples_2
python get_examples.py -i dataset\rmcoll -d examples_2
python get_examples.py -i dataset\rmpugh -d examples_2
python get_examples.py -i dataset\rnpwil -d examples_2
python get_examples.py -i dataset\robin -d examples_2
python get_examples.py -i dataset\rrowle -d examples_2
python get_examples.py -i dataset\rsanti -d examples_2
python get_examples.py -i dataset\saduah -d examples_2
python get_examples.py -i dataset\saedwa -d examples_2
python get_examples.py -i dataset\sandm -d examples_2
python get_examples.py -i dataset\sbains -d examples_2
python get_examples.py -i dataset\sidick -d examples_2
python get_examples.py -i dataset\sjbeck -d examples_2
python get_examples.py -i dataset\skumar -d examples_2
python get_examples.py -i dataset\slbirc -d examples_2
python get_examples.py -i dataset\smrobb -d examples_2
python get_examples.py -i dataset\son_tung -d examples_2
python get_examples.py -i dataset\spacl -d examples_2
python get_examples.py -i dataset\spletc -d examples_2
python get_examples.py -i dataset\svkriz -d examples_2
python get_examples.py -i dataset\swewin -d examples_2
python get_examples.py -i dataset\swsmit -d examples_2
python get_examples.py -i dataset\tony -d examples_2
python get_examples.py -i dataset\truong_giang -d examples_2
python get_examples.py -i dataset\voudcx -d examples_2
python get_examples.py -i dataset\vpsavo -d examples_2
python get_examples.py -i dataset\vstros -d examples_2
python get_examples.py -i dataset\whussa -d examples_2
python get_examples.py -i dataset\wjalbe -d examples_2
python get_examples.py -i dataset\yfhsie -d examples_2