python get_examples.py -i dataset\9326871 -d examples
python get_examples.py -i dataset\9332898 -d examples
python get_examples.py -i dataset\9336923 -d examples
python get_examples.py -i dataset\9338446 -d examples
python get_examples.py -i dataset\9338454 -d examples
python get_examples.py -i dataset\9338462 -d examples
python get_examples.py -i dataset\9338489 -d examples
python get_examples.py -i dataset\9338497 -d examples
python get_examples.py -i dataset\9338519 -d examples
python get_examples.py -i dataset\9338527 -d examples
python get_examples.py -i dataset\9338535 -d examples
python get_examples.py -i dataset\9338543 -d examples
python get_examples.py -i dataset\9414649 -d examples
python get_examples.py -i dataset\9416994 -d examples
python get_examples.py -i dataset\adhast -d examples
python get_examples.py -i dataset\admars -d examples
python get_examples.py -i dataset\ahodki -d examples
python get_examples.py -i dataset\ajbake -d examples
python get_examples.py -i dataset\ajflem -d examples
python get_examples.py -i dataset\ajones -d examples
python get_examples.py -i dataset\ajsega -d examples
python get_examples.py -i dataset\akatsi -d examples
python get_examples.py -i dataset\alan_grant -d examples
python get_examples.py -i dataset\ambarw -d examples
python get_examples.py -i dataset\anonym -d examples
python get_examples.py -i dataset\anonym1 -d examples
python get_examples.py -i dataset\anonym2 -d examples
python get_examples.py -i dataset\anpage -d examples
python get_examples.py -i dataset\apapou -d examples
python get_examples.py -i dataset\apdavi -d examples
python get_examples.py -i dataset\ardper -d examples
python get_examples.py -i dataset\asamma -d examples
python get_examples.py -i dataset\asewil -d examples
python get_examples.py -i dataset\asheal -d examples
python get_examples.py -i dataset\astefa -d examples
python get_examples.py -i dataset\awjsud -d examples
python get_examples.py -i dataset\boylee -d examples
python get_examples.py -i dataset\bplyce -d examples
python get_examples.py -i dataset\bschap -d examples
python get_examples.py -i dataset\cadugd -d examples
python get_examples.py -i dataset\cchris -d examples
python get_examples.py -i dataset\ccjame -d examples
python get_examples.py -i dataset\cdlarg -d examples
python get_examples.py -i dataset\cferdo -d examples
python get_examples.py -i dataset\cfloro -d examples
python get_examples.py -i dataset\cgboyc -d examples
python get_examples.py -i dataset\chi_pu -d examples
python get_examples.py -i dataset\cjcarr -d examples
python get_examples.py -i dataset\cjdenn -d examples
python get_examples.py -i dataset\cjsake -d examples
python get_examples.py -i dataset\cladam -d examples
python get_examples.py -i dataset\cmkirk -d examples
python get_examples.py -i dataset\csanch -d examples
python get_examples.py -i dataset\cshubb -d examples
python get_examples.py -i dataset\cwang -d examples
python get_examples.py -i dataset\cwchoi -d examples
python get_examples.py -i dataset\cywan -d examples
python get_examples.py -i dataset\dagran -d examples
python get_examples.py -i dataset\dakram -d examples
python get_examples.py -i dataset\damvo -d examples
python get_examples.py -i dataset\darda -d examples
python get_examples.py -i dataset\dcbowe -d examples
python get_examples.py -i dataset\dfhodd -d examples
python get_examples.py -i dataset\dgemen -d examples
python get_examples.py -i dataset\dioann -d examples
python get_examples.py -i dataset\djbirc -d examples
python get_examples.py -i dataset\djhugh -d examples
python get_examples.py -i dataset\djmart -d examples
python get_examples.py -i dataset\dmwest -d examples
python get_examples.py -i dataset\doraj -d examples
python get_examples.py -i dataset\drbost -d examples
python get_examples.py -i dataset\ekavaz -d examples
python get_examples.py -i dataset\elduns -d examples
python get_examples.py -i dataset\fordj -d examples
python get_examples.py -i dataset\gdhatc -d examples
python get_examples.py -i dataset\ggeorg -d examples
python get_examples.py -i dataset\ggrego -d examples
python get_examples.py -i dataset\gjhero -d examples
python get_examples.py -i dataset\gjnorm -d examples
python get_examples.py -i dataset\gmwate -d examples
python get_examples.py -i dataset\gotone -d examples
python get_examples.py -i dataset\gpapaz -d examples
python get_examples.py -i dataset\gpsmit -d examples
python get_examples.py -i dataset\gsmall -d examples
python get_examples.py -i dataset\gsreas -d examples
python get_examples.py -i dataset\gstamo -d examples
python get_examples.py -i dataset\gsvird -d examples
python get_examples.py -i dataset\hartb -d examples
python get_examples.py -i dataset\hcarpe -d examples
python get_examples.py -i dataset\hensm -d examples
python get_examples.py -i dataset\howar -d examples
python get_examples.py -i dataset\hsgrim -d examples
python get_examples.py -i dataset\huynh_lap -d examples
python get_examples.py -i dataset\ieorf -d examples
python get_examples.py -i dataset\ijfran -d examples
python get_examples.py -i dataset\irdrew -d examples
python get_examples.py -i dataset\isbald -d examples
python get_examples.py -i dataset\jabins -d examples
python get_examples.py -i dataset\jagrif -d examples
python get_examples.py -i dataset\jbierl -d examples
python get_examples.py -i dataset\jcarte -d examples
python get_examples.py -i dataset\jdbenm -d examples
python get_examples.py -i dataset\jgloma -d examples
python get_examples.py -i dataset\jlemon -d examples
python get_examples.py -i dataset\jmedin -d examples
python get_examples.py -i dataset\jross -d examples
python get_examples.py -i dataset\jrtobi -d examples
python get_examples.py -i dataset\jserai -d examples
python get_examples.py -i dataset\jshea -d examples
python get_examples.py -i dataset\justin_bieber -d examples
python get_examples.py -i dataset\kaatki -d examples
python get_examples.py -i dataset\kaknig -d examples
python get_examples.py -i dataset\kbartl -d examples
python get_examples.py -i dataset\kdjone -d examples
python get_examples.py -i dataset\khchan -d examples
python get_examples.py -i dataset\khughe -d examples
python get_examples.py -i dataset\kjwith -d examples
python get_examples.py -i dataset\klclar -d examples
python get_examples.py -i dataset\kmbald -d examples
python get_examples.py -i dataset\kouri -d examples
python get_examples.py -i dataset\ksunth -d examples
python get_examples.py -i dataset\labenm -d examples
python get_examples.py -i dataset\ldgodd -d examples
python get_examples.py -i dataset\lejnno -d examples
python get_examples.py -i dataset\lfso -d examples
python get_examples.py -i dataset\lidov -d examples
python get_examples.py -i dataset\llambr -d examples
python get_examples.py -i dataset\lyond -d examples
python get_examples.py -i dataset\maasht -d examples
python get_examples.py -i dataset\macci -d examples
python get_examples.py -i dataset\martin -d examples
python get_examples.py -i dataset\matth -d examples
python get_examples.py -i dataset\mberdo -d examples
python get_examples.py -i dataset\mbutle -d examples
python get_examples.py -i dataset\mdchud -d examples
python get_examples.py -i dataset\mdpove -d examples
python get_examples.py -i dataset\mefait -d examples
python get_examples.py -i dataset\mhwill -d examples
python get_examples.py -i dataset\miaduc -d examples
python get_examples.py -i dataset\michael -d examples
python get_examples.py -i dataset\mizli -d examples
python get_examples.py -i dataset\mjhans -d examples
python get_examples.py -i dataset\mkosto -d examples
python get_examples.py -i dataset\moors -d examples
python get_examples.py -i dataset\mpetti -d examples
python get_examples.py -i dataset\muthay -d examples
python get_examples.py -i dataset\nahaig -d examples
python get_examples.py -i dataset\namull -d examples
python get_examples.py -i dataset\ndbank -d examples
python get_examples.py -i dataset\ndhagu -d examples
python get_examples.py -i dataset\ngo_kien_huy -d examples
python get_examples.py -i dataset\nhrams -d examples
python get_examples.py -i dataset\njmoor -d examples
python get_examples.py -i dataset\npbour -d examples
python get_examples.py -i dataset\npmitc -d examples
python get_examples.py -i dataset\nrclar -d examples
python get_examples.py -i dataset\nrrbar -d examples
python get_examples.py -i dataset\nwilli -d examples
python get_examples.py -i dataset\obeidn -d examples
python get_examples.py -i dataset\ohpark -d examples
python get_examples.py -i dataset\pacole -d examples
python get_examples.py -i dataset\phughe -d examples
python get_examples.py -i dataset\pmives -d examples
python get_examples.py -i dataset\pshurr -d examples
python get_examples.py -i dataset\pspliu -d examples
python get_examples.py -i dataset\ptnich -d examples
python get_examples.py -i dataset\rarobi -d examples
python get_examples.py -i dataset\rgharr -d examples
python get_examples.py -i dataset\rgspru -d examples
python get_examples.py -i dataset\rjlabr -d examples
python get_examples.py -i dataset\rlocke -d examples
python get_examples.py -i dataset\rmcoll -d examples
python get_examples.py -i dataset\rmpugh -d examples
python get_examples.py -i dataset\rnpwil -d examples
python get_examples.py -i dataset\robin -d examples
python get_examples.py -i dataset\rrowle -d examples
python get_examples.py -i dataset\rsanti -d examples
python get_examples.py -i dataset\saduah -d examples
python get_examples.py -i dataset\saedwa -d examples
python get_examples.py -i dataset\sandm -d examples
python get_examples.py -i dataset\sbains -d examples
python get_examples.py -i dataset\sidick -d examples
python get_examples.py -i dataset\sjbeck -d examples
python get_examples.py -i dataset\skumar -d examples
python get_examples.py -i dataset\slbirc -d examples
python get_examples.py -i dataset\smrobb -d examples
python get_examples.py -i dataset\son_tung -d examples
python get_examples.py -i dataset\spacl -d examples
python get_examples.py -i dataset\spletc -d examples
python get_examples.py -i dataset\svkriz -d examples
python get_examples.py -i dataset\swewin -d examples
python get_examples.py -i dataset\swsmit -d examples
python get_examples.py -i dataset\tony -d examples
python get_examples.py -i dataset\truong_giang -d examples
python get_examples.py -i dataset\voudcx -d examples
python get_examples.py -i dataset\vpsavo -d examples
python get_examples.py -i dataset\vstros -d examples
python get_examples.py -i dataset\whussa -d examples
python get_examples.py -i dataset\wjalbe -d examples
python get_examples.py -i dataset\yfhsie -d examples